### ISSUE TITLE
Translation and some bugs

### ISSUE THREAD

**Issue by Stars-Azusa** [Gaming12846/TrollPlus#3]
(I'm from China, there may be issues with my English. Sorry)
Here's a fully translation file for Chinese Simplified. (Rename it to .yml to use). I fix something that isn't be translated by the previous translator. I hope you can update this.
[lang_zhcn.txt](https://github.com/Gaming12846/TrollPlus/files/12136174/lang_zhcn.txt)
Bugs:
1. Some config and translation changes can't be loaded after using reload command. In order to load changes, you need to reload the 
whole plugin.
2. Messages like "vanish-quit-message""spam-messages" is defined in config.yml instead of lang_xx.yml.

**Comment by Gaming12846** [comment]
Hello RinoRika,
thanks for your support with translating the plugin and submitting the issues. After adding your translation file and fixing the issues, I will release a fix for the plugin.

**Comment by Gaming12846** [comment]
Can you specify which settings and translations are not being reloaded?

**Comment by Stars-Azusa** [comment]
It seems like that after the first reload, nothing was changed.
After the second reload, the language *parts* like "trollplus""troll""troll-gui" was loaded correctly,
but some translation without big part like "metrics-enabled""invalid-syntax" wasn't loaded.

**Comment by Stars-Azusa** [comment]
Oh, you need to reload twice, and everything except "Global" translation part will be loaded

**Comment by Stars-Azusa** [comment]
I found you added "features translations" to language, so I translated it for the update.
[lang_zhcn.txt](https://github.com/Gaming12846/TrollPlus/files/12138553/lang_zhcn.txt)

**Comment by Gaming12846** [comment]
Thanks I added it to the language file and I found the problem and I am working on it.

**Comment by Gaming12846** [comment]
I fixed the Problem with the latest commits. I will release a new version soon.
